/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerProduto;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.EventListener;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author junio
 */
public final class PainelVendas extends javax.swing.JFrame {

    private List<Produto> produtos;

    /**
     * Creates new form PainelVendas
     */
    public PainelVendas() {
        initComponents();
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamTela = kit.getScreenSize();
        int larg = tamTela.width;
        int alt = tamTela.height;
        this.setSize(larg, alt);
        this.setLocationRelativeTo(null);
        this.getBounds();
        jTcodigo.grabFocus();
        atualizaHoras();
        produtos = new ArrayList();

        jTcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    PegarDados();

                }

            }
        });

    }
 
    private void atualizaHoras() {
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                SimpleDateFormat formato = new SimpleDateFormat("dd/MM/YYYY H:mm:ss - a");
                String dataFormatada = formato.format(new Date());
                jLabel5.setText(dataFormatada);
            }
        };
        Timer timer = new Timer();
        timer.schedule(task, new Date(), 1000);
    }
    private void PegarDados() {
        String codigo = jTcodigo.getText();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!");
            return;
        }
        boolean produtoJaExiste = false;
        for (Produto produto : produtos) {
            if (produto.getCodigo().equals(codigo)) {
                produto.setQuantidade(produto.getQuantidade() + 1);
                produtoJaExiste = true;
            }
        }
        if (produtoJaExiste) {
            jTcodigo.setText("");
            atualizarValorTotal();
            atualizarTabela();
            return;
        }
        ControllerProduto cp = new ControllerProduto();
        try {
            Produto produto = cp.bucarProduto(codigo);
            if (produto == null) {
                JOptionPane.showMessageDialog(null,
                        "Produto nao encontrado!!");
                return;
            }
            produto.setQuantidade(1);
            produtos.add(produto);
            jTcodigo.setText("");
            atualizarValorTotal();
            atualizarTabela();
        } catch (SQLException ex) {
            Logger.getLogger(PainelVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /**
     *
     * @param nome the value of nome
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jbEditQtd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTcodigo = new javax.swing.JTextField();
        jBvender = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JLvalor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txAM = new javax.swing.JTable();
        jButtonFinaliza = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLTroco = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLdata = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/11697ghghfgvbfgfgfg59659645945.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                formAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-página-inicial-50.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbEditQtd.setText("Edite a quantidade");
        jbEditQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditQtdActionPerformed(evt);
            }
        });
        jPanel1.add(jbEditQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jButton2.setText("Deletar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jTcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTcodigoFocusGained(evt);
            }
        });
        jTcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodigoActionPerformed(evt);
            }
        });
        jTcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTcodigoKeyPressed(evt);
            }
        });
        jPanel1.add(jTcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 120, -1));

        jBvender.setText("Vender!");
        jBvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvenderActionPerformed(evt);
            }
        });
        jBvender.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBvenderKeyPressed(evt);
            }
        });
        jPanel1.add(jBvender, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, -1));

        jLabel2.setText("Codigo de Barras:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 20));

        JLvalor.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JLvalor.setForeground(new java.awt.Color(0, 0, 0));
        JLvalor.setText("R$: 0,0");
        jPanel1.add(JLvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 420, 50));

        txAM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Codigo", "Quantidade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        txAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txAMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txAM);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 600, -1));

        jButtonFinaliza.setText("Finalizar");
        jButtonFinaliza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFinalizaMouseClicked(evt);
            }
        });
        jButtonFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFinaliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jButton1.setText("Caucular Troco");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, -1));

        jLTroco.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTroco.setForeground(new java.awt.Color(0, 0, 0));
        jLTroco.setText("R$");
        jPanel1.add(jLTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 190, 50));

        jToggleButton1.setText("Desconto!");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, -1));

        jLdata.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLdata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/painelVendas.png"))); // NOI18N
        jPanel1.add(jLdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 810));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/painelVendas.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imprimir() {
        String dataf = "dd/MM/YYYY";
        String horaf = "H:mm - a";
        String data, hora;
        java.util.Date dataAtual = new java.util.Date();
        SimpleDateFormat formatar = new SimpleDateFormat(dataf);
        data = formatar.format(dataAtual);
        formatar = new SimpleDateFormat(horaf);
        hora = formatar.format(dataAtual);
        JOptionPane.showMessageDialog(null, data + hora);

    }


    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jButtonFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFinalizaActionPerformed

    private void jButtonFinalizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFinalizaMouseClicked
        ControllerProduto controllerP = new ControllerProduto();
        controllerP.subtrairDoBanco(produtos);
        try {
            cadastraVenda();
            //imprimir();
        } catch (ParseException ex) {
            Logger.getLogger(PainelVendas.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(PainelVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonFinalizaMouseClicked

    private void txAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txAMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txAMMouseClicked

    private void jBvenderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBvenderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBvenderKeyPressed

    @SuppressWarnings("empty-statement")
    private void jBvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvenderActionPerformed
        // TODO add your handling code here:
        PegarDados();
    }//GEN-LAST:event_jBvenderActionPerformed

    private void jTcodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcodigoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodigoKeyPressed

    private void jTcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodigoActionPerformed

    private void jTcodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcodigoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcodigoFocusGained

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cadastraVenda() throws Exception {
        ControllerProduto cp = new ControllerProduto();
        Produto produto = new Produto();
        String data = "dd/MM/YYYY H:mm - a";
        String data1;
        SimpleDateFormat formato = new SimpleDateFormat(data);
        Date tmpoAtual = new Date();
        data1 = formato.format(tmpoAtual);

        ArrayList<Produto> ppproduto = new ArrayList();

        for (Produto pproduto : produtos) {
            produto.setNome(pproduto.getNome());
            produto.setCodigo(pproduto.getCodigo());
            produto.setValorEntrada(pproduto.getValorEntrada());
            produto.setValorS(pproduto.calcularValor());
            produto.setQuantidade(pproduto.getQuantidade());
            pproduto.setTotal(pproduto.mutiplicar(pproduto.getQuantidade()));
            pproduto.setHorario(data1);
            ppproduto.add(pproduto);

        }

        cp.cadastrarVenda((ArrayList<Produto>) ppproduto);

        produtos.clear();
        atualizarValorTotal();
        atualizarTabela();

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int selection = txAM.getSelectedRow();
        produtos.remove(selection);
        atualizarTabela();
        atualizarValorTotal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbEditQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditQtdActionPerformed
        EditaQuantidade();
    }//GEN-LAST:event_jbEditQtdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        PainelPrincipal pp = new PainelPrincipal();
        pp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void funcaoTroco() {
        String valorMaior = JOptionPane.showInputDialog("Digite o valor!");
        String valor = JLvalor.getText();
        String novovalor = "";
        for (String valores : valor.split("[^0-9]")) {
            novovalor += valores;
        }
        double valorSubiraindo = Double.parseDouble(
                valorMaior) - Double.parseDouble(
                        novovalor) / 100;
        jLTroco.setText(formatarParaReal(valorSubiraindo));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        funcaoTroco();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        desconto();
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    private void desconto(){
        Produto ppp = new Produto();
        String desconto = JOptionPane.
                showInputDialog(this,
                "Quantos de desconto em %");
        double descontodouble = Double.parseDouble(desconto);
        double valors = 0;
         for (Produto produto:produtos){
            valors = produto.getValorS();
            produto.setValorS(valors - descontodouble * valors / 100);
             
         }
        
         atualizarTabela();
         atualizarValorTotal();
    
        
    }
    private void atualizarTabela() {
        Produto p = new Produto();
        DefaultTableModel modelo = new DefaultTableModel();

        modelo.addColumn("Nome");
        modelo.addColumn("Codigo");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Valor");

        for (Produto produto : produtos) {

            double valor = produto.mutiplicar(produto.getQuantidade());
            modelo.addRow(new Object[]{
                produto.getNome(),
                produto.getCodigo(),
                produto.getQuantidade(),
                formatarParaReal(valor)
            });

        }
        txAM.setModel(modelo);

    }

    private void atualizarValorTotal() {
        Produto pro = new Produto();
        double soma = 0;
        for (Produto produto : produtos) {
            double valor = produto.mutiplicar(produto.getQuantidade());
            soma += valor;
        }
        pro.setTotal(soma);
        JLvalor.setText(formatarParaReal(soma));

    }

    private String formatarParaReal(double valor) {
        DecimalFormat df = new DecimalFormat("#,##0.00");
        return "R$ " + df.format(valor);
    }

    private void EditaQuantidade() {
        int selection = txAM.getSelectedRow();
        String numero = JOptionPane.showInputDialog("Digite a quantidade!");
        int quantidade = Integer.parseInt(numero);
        Produto produto = produtos.get(selection);
        produto.setQuantidade(quantidade);
        atualizarTabela();
        atualizarValorTotal();
    }

    /**
     *
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PainelVendas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLvalor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonFinaliza;
    private javax.swing.JButton jBvender;
    private javax.swing.JLabel jLTroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLdata;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTcodigo;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton jbEditQtd;
    private javax.swing.JTable txAM;
    // End of variables declaration//GEN-END:variables
}
